### ISSUE TITLE
Videoexport is non existent and i kinda want a fix

### ISSUE THREAD

**Issue by jmxamongusmodder** [carykh/BFDIA7intro#1]

**Comment by jmxamongusmodder** [comment]
nvm got the library but now i get this

RuntimeException: java.lang.NoSuchFieldError: frame
java.lang.RuntimeException: java.lang.NoSuchFieldError: frame
	at processing.opengl.PSurfaceJOGL.lambda$initAnimator$2(PSurfaceJOGL.java:430)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoSuchFieldError: frame
	at com.hamoid.VideoExport.initialize(Unknown Source)
	at com.hamoid.VideoExport.startMovie(Unknown Source)
	at BFDIA7intro.setup(BFDIA7intro.java:127)
	at processing.core.PApplet.handleDraw(PApplet.java:2051)
	at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:840)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:782)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:453)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
RuntimeException: java.lang.NoSuchFieldError: frame

**Comment by UrkiMimi** [comment]
A temporary band aid fix is to comment out line 108 in the main Processing file. The thing runs fine but no longer renders to a video file and instead renders in real time.

<img width="264" alt="Screenshot 2023-11-02 at 7 11 45 PM" src="https://github.com/carykh/BFDIA7intro/assets/74517821/f834ecea-f29a-41de-8871-1e528c3bd1a0">

EDIT: I was able to run the file and save the rendered video on my iMac just fine. I'm not exactly sure what caused me to get this error on my laptop but the thing still ran without an issue.
